name: authentication_and_authorization_frontend
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  bloc: ^8.1.0
  hive: ^2.2.3
  equatable: ^2.0.3
  bloc_test: ^9.1.0
  fluttertoast: ^8.0.9
  flutter_bloc: ^8.1.1
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.0.2
  flutter_modular: ^5.0.3
  cupertino_icons: ^1.0.2
  auto_route_generator: ^4.2.1
  flutter_secure_storage: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
